import { ProcessedData } from '../store/dataStore';
import { saveAs } from 'file-saver';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { marked } from 'marked';

interface ReportData {
  processedData: ProcessedData;
  timestamp: Date;
}

export async function generateAnalyticsReport(reportData: ReportData) {
  const { processedData, timestamp } = reportData;
  const { summary, headers, rows } = processedData;

  try {
    // Generate AI-powered insights
    const aiInsights = await generateAIInsights(processedData);
    
    // Generate comprehensive report content with AI insights
    let reportContent = `
AI-POWERED DATA INSIGHTS REPORT
Generated on: ${timestamp.toLocaleDateString()} at ${timestamp.toLocaleTimeString()}
================================================================================

DATASET OVERVIEW
================================================================================
• Total Rows: ${summary.rowCount.toLocaleString()}
• Total Columns: ${summary.columnCount.toLocaleString()}
• Numerical Columns: ${summary.numericalColumns.length} (${((summary.numericalColumns.length / summary.columnCount) * 100).toFixed(1)}%)
• Categorical Columns: ${summary.categoricalColumns.length} (${((summary.categoricalColumns.length / summary.columnCount) * 100).toFixed(1)}%)

COLUMN INFORMATION
================================================================================
All Columns: ${headers.join(', ')}
Numerical Columns: ${summary.numericalColumns.join(', ') || 'None'}
Categorical Columns: ${summary.categoricalColumns.join(', ') || 'None'}

DETAILED COLUMN STATISTICS
================================================================================
${Object.entries(summary.columnStats).map(([column, stats]: [string, any]) => {
  if (summary.numericalColumns.includes(column)) {
    return `
${column.toUpperCase()} (Numerical)
----------------------------------------
• Range: ${stats.min} to ${stats.max}
• Mean: ${stats.mean?.toFixed(2)} | Median: ${stats.median?.toFixed(2)}
• Standard Deviation: ${stats.stdDev?.toFixed(2)}
• Total Count: ${stats.totalCount}
`;
  } else {
    return `
${column.toUpperCase()} (Categorical)
----------------------------------------
• Unique Values: ${stats.uniqueValues}
• Total Count: ${stats.totalCount}
• Top Values: ${stats.mostCommon?.slice(0, 3).map((item: any) => 
  `${item.value} (${item.percentage.toFixed(1)}%)`
).join(', ') || 'No data available'}
`;
  }
}).join('\n')}

AI-GENERATED INSIGHTS & ANALYSIS
================================================================================
${aiInsights}

DATA QUALITY ASSESSMENT
================================================================================
${analyzeDataQuality(processedData)}

DATA SAMPLE (First 10 Rows)
================================================================================
${generateDataSample(processedData)}

================================================================================
Report generated by DataAnalytics AI Platform
Dataset contains ${rows.length.toLocaleString()} rows across ${headers.length} columns
Analysis powered by advanced AI insights generation
================================================================================
`;

    return reportContent;
    
  } catch (error) {
    console.error('Error generating AI insights:', error);
    
    // Fallback to basic report if AI fails
    return generateBasicReport(reportData);
  }
}

function analyzeDataQuality(data: ProcessedData): string {
  const { rows, headers } = data;
  let qualityReport = '';

  // Check for missing values
  const missingValueCounts: Record<string, number> = {};
  headers.forEach(header => {
    missingValueCounts[header] = rows.filter(row => 
      row[header] === null || row[header] === undefined || row[header] === ''
    ).length;
  });

  qualityReport += 'Missing Values Analysis:\n';
  Object.entries(missingValueCounts).forEach(([column, count]) => {
    const percentage = (count / rows.length) * 100;
    if (count > 0) {
      qualityReport += `• ${column}: ${count} missing (${percentage.toFixed(1)}%)\n`;
    }
  });

  // Data completeness score
  const totalValues = headers.length * rows.length;
  const missingValues = Object.values(missingValueCounts).reduce((sum, count) => sum + count, 0);
  const completenessScore = ((totalValues - missingValues) / totalValues) * 100;
  
  qualityReport += `\nOverall Data Completeness: ${completenessScore.toFixed(1)}%\n`;
  
  if (completenessScore >= 95) {
    qualityReport += 'Quality Rating: Excellent - Very few missing values\n';
  } else if (completenessScore >= 85) {
    qualityReport += 'Quality Rating: Good - Some missing values present\n';
  } else if (completenessScore >= 70) {
    qualityReport += 'Quality Rating: Fair - Significant missing values that may affect analysis\n';
  } else {
    qualityReport += 'Quality Rating: Poor - High number of missing values. Analysis may be unreliable.\n';
  }

  return qualityReport;
}

function generateStatisticalInsights(data: ProcessedData): string {
  const { summary } = data;
  let insights = '';

  // Numerical insights
  if (summary.numericalColumns.length > 0) {
    insights += 'Numerical Data Insights:\n';
    summary.numericalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.mean && stats.stdDev) {
        const cv = (stats.stdDev / stats.mean) * 100; // Coefficient of variation
        insights += `• ${column}: `;
        if (cv < 15) {
          insights += 'Low variability (stable values)\n';
        } else if (cv < 30) {
          insights += 'Moderate variability\n';
        } else {
          insights += 'High variability (diverse values)\n';
        }
      }
    });
  }

  // Categorical insights
  if (summary.categoricalColumns.length > 0) {
    insights += '\nCategorical Data Insights:\n';
    summary.categoricalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.uniqueValues && stats.totalCount) {
        const diversity = (stats.uniqueValues / stats.totalCount) * 100;
        insights += `• ${column}: `;
        if (diversity < 10) {
          insights += 'Low diversity (few unique values)\n';
        } else if (diversity < 50) {
          insights += 'Moderate diversity\n';
        } else {
          insights += 'High diversity (many unique values)\n';
        }
      }
    });
  }

  return insights;
}

function analyzeCorrelations(data: ProcessedData): string {
  const { summary, rows } = data;
  let correlationReport = '';

  if (summary.numericalColumns.length >= 2) {
    correlationReport += 'Numerical Column Relationships:\n';
    
    // Simple correlation analysis for first few numerical columns
    const numCols = summary.numericalColumns.slice(0, 3); // Limit to first 3 for performance
    
    for (let i = 0; i < numCols.length; i++) {
      for (let j = i + 1; j < numCols.length; j++) {
        const col1 = numCols[i];
        const col2 = numCols[j];
        
        // Calculate basic correlation indicator
        const values1 = rows.map(row => Number(row[col1])).filter(v => !isNaN(v));
        const values2 = rows.map(row => Number(row[col2])).filter(v => !isNaN(v));
        
        if (values1.length > 0 && values2.length > 0) {
          const mean1 = values1.reduce((sum, v) => sum + v, 0) / values1.length;
          const mean2 = values2.reduce((sum, v) => sum + v, 0) / values2.length;
          
          correlationReport += `• ${col1} vs ${col2}: Data available for analysis\n`;
        }
      }
    }
  } else {
    correlationReport += 'Insufficient numerical columns for correlation analysis.\n';
  }

  return correlationReport;
}

function generateRecommendations(data: ProcessedData): string {
  const { summary, rows } = data;
  let recommendations = '';

  // Dataset size recommendations
  if (rows.length < 100) {
    recommendations += '• Consider collecting more data points for better statistical reliability\n';
  } else if (rows.length > 10000) {
    recommendations += '• Large dataset detected - consider sampling for faster analysis\n';
  }

  // Column recommendations
  if (summary.numericalColumns.length === 0) {
    recommendations += '• No numerical columns found - consider converting categorical data to numerical for statistical analysis\n';
  }

  if (summary.categoricalColumns.length === 0) {
    recommendations += '• No categorical columns found - consider grouping numerical data into categories for pattern analysis\n';
  }

  // Data quality recommendations
  const avgUniqueValues = summary.categoricalColumns.reduce((sum, col) => {
    return sum + (summary.columnStats[col].uniqueValues || 0);
  }, 0) / Math.max(summary.categoricalColumns.length, 1);

  if (avgUniqueValues > rows.length * 0.8) {
    recommendations += '• High number of unique categorical values - consider data consolidation\n';
  }

  if (recommendations === '') {
    recommendations = '• Dataset appears well-structured for analysis\n• Consider exploring visualizations for deeper insights\n';
  }

  return recommendations;
}

function generateDataSample(data: ProcessedData): string {
  const { headers, rows } = data;
  let sample = '';

  // Header row
  sample += headers.join(' | ') + '\n';
  sample += headers.map(h => '-'.repeat(h.length)).join('-|-') + '\n';

  // First 10 rows
  const sampleRows = rows.slice(0, 10);
  sampleRows.forEach(row => {
    const rowValues = headers.map(header => {
      const value = row[header];
      if (value === null || value === undefined) return 'NULL';
      const stringValue = String(value);
      if (stringValue.length > 30) {
        return stringValue.substring(0, 27) + '...';
      }
      return stringValue;
    });
    sample += rowValues.join(' | ') + '\n';
  });

  if (rows.length > 10) {
    sample += `\n... and ${rows.length - 10} more rows\n`;
  }

  return sample;
}

export async function downloadAnalyticsReport(processedData: ProcessedData) {
  try {
    const reportData: ReportData = {
      processedData,
      timestamp: new Date()
    };

    const reportContent = await generateAnalyticsReport(reportData);
    
    // Create and download the report file
    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const fileName = `insights-report-${new Date().toISOString().split('T')[0]}.txt`;
    
    saveAs(blob, fileName);
    
    return { success: true, fileName };
  } catch (error) {
    console.error('Error generating analytics report:', error);
    throw new Error('Failed to generate analytics report');
  }
}

export async function downloadAnalyticsReportHTML(processedData: ProcessedData) {
  try {
    const reportData: ReportData = {
      processedData,
      timestamp: new Date()
    };

    // Generate AI-powered insights in Markdown format
    const aiInsightsMarkdown = await generateAIInsights(processedData);

    // Sanitize and parse the Markdown to HTML
    const aiInsightsHtml = marked.parse(aiInsightsMarkdown);

    // Get the basic report summary
    const basicReport = generateBasicReport(reportData);
    
    // Convert to HTML format
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-Powered Data Insights Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            background-color: #0d1117;
            color: #c9d1d9;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: #161b22;
            padding: 20px 40px;
            border-radius: 10px;
            border: 1px solid #30363d;
        }
        h1, h2, h3, h4 {
            color: #58a6ff;
            border-bottom: 1px solid #30363d;
            padding-bottom: 8px;
            margin-top: 24px;
        }
        h1 { font-size: 2em; text-align: center; border: none; }
        h2 { font-size: 1.5em; }
        h3 { font-size: 1.25em; border-bottom-style: dashed; }
        h4 { font-size: 1.1em; color: #8b949e; border: none; }

        p {
            margin-bottom: 16px;
        }

        ul {
            padding-left: 20px;
        }
        li {
            margin-bottom: 8px;
        }

        strong {
            color: #8b949e;
        }

        pre {
            background: #0d1117;
            padding: 15px;
            border-radius: 5px;
            border: 1px solid #30363d;
            overflow-x: auto;
            font-family: 'Courier New', Courier, monospace;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        code {
          background-color: rgba(135,142,148,0.15);
          padding: .2em .4em;
          margin: 0;
          font-size: 85%;
          border-radius: 6px;
        }
        .timestamp {
            text-align: center;
            color: #8b949e;
            font-style: italic;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 AI-Powered Insights Report</h1>
        <div class="timestamp">Generated on ${reportData.timestamp.toLocaleDateString()} at ${reportData.timestamp.toLocaleTimeString()}</div>
        
        <div class="section">
          ${aiInsightsHtml}
        </div>

        <div class="section">
          <h2>Base Data Summary</h2>
          <pre>${basicReport}</pre>
        </div>
    </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const fileName = `insights-report-${new Date().toISOString().split('T')[0]}.html`;
    
    saveAs(blob, fileName);
    
    return { success: true, fileName };
  } catch (error) {
    console.error('Error generating HTML analytics report:', error);
    throw new Error('Failed to generate HTML analytics report');
  }
}

function generateDetailedInsights(data: ProcessedData): string {
  const { summary, rows, headers } = data;
  let insights = '';

  // Overall data characteristics
  insights += 'Dataset Characteristics:\n';
  insights += `• Dataset Size: ${rows.length > 10000 ? 'Large' : rows.length > 1000 ? 'Medium' : 'Small'} dataset with ${rows.length.toLocaleString()} records\n`;
  insights += `• Data Complexity: ${headers.length > 20 ? 'High' : headers.length > 10 ? 'Medium' : 'Low'} complexity with ${headers.length} attributes\n`;
  
  const numRatio = summary.numericalColumns.length / headers.length;
  if (numRatio > 0.7) {
    insights += '• Data Type: Predominantly numerical data - well-suited for statistical analysis and machine learning\n';
  } else if (numRatio > 0.3) {
    insights += '• Data Type: Mixed data types - good balance for comprehensive analysis\n';
  } else {
    insights += '• Data Type: Predominantly categorical data - ideal for classification and pattern analysis\n';
  }

  // Numerical insights
  if (summary.numericalColumns.length > 0) {
    insights += '\nNumerical Data Analysis:\n';
    
    summary.numericalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.mean && stats.stdDev && stats.min !== undefined && stats.max !== undefined) {
        const range = stats.max - stats.min;
        const cv = (stats.stdDev / stats.mean) * 100;
        
        insights += `• ${column}:\n`;
        insights += `  - Range: ${range.toFixed(2)} (${stats.min} to ${stats.max})\n`;
        insights += `  - Average: ${stats.mean.toFixed(2)}\n`;
        insights += `  - Variability: ${cv < 15 ? 'Low' : cv < 30 ? 'Moderate' : 'High'} (CV: ${cv.toFixed(1)}%)\n`;
        
        if (stats.mean > (stats.min + stats.max) / 2) {
          insights += `  - Distribution: Data tends toward higher values\n`;
        } else if (stats.mean < (stats.min + stats.max) / 2) {
          insights += `  - Distribution: Data tends toward lower values\n`;
        } else {
          insights += `  - Distribution: Data is fairly centered\n`;
        }
      }
    });
  }

  // Categorical insights
  if (summary.categoricalColumns.length > 0) {
    insights += '\nCategorical Data Analysis:\n';
    
    summary.categoricalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.uniqueValues && stats.totalCount && stats.mostCommon) {
        const diversity = (stats.uniqueValues / stats.totalCount) * 100;
        const topCategory = stats.mostCommon[0];
        
        insights += `• ${column}:\n`;
        insights += `  - Categories: ${stats.uniqueValues} unique values\n`;
        insights += `  - Diversity: ${diversity < 10 ? 'Low' : diversity < 50 ? 'Moderate' : 'High'} (${diversity.toFixed(1)}%)\n`;
        insights += `  - Dominant Category: "${topCategory.value}" (${topCategory.percentage.toFixed(1)}% of data)\n`;
        
        if (topCategory.percentage > 70) {
          insights += `  - Distribution: Highly skewed toward "${topCategory.value}"\n`;
        } else if (topCategory.percentage > 40) {
          insights += `  - Distribution: Moderately concentrated\n`;
        } else {
          insights += `  - Distribution: Well distributed across categories\n`;
        }
      }
    });
  }

  return insights;
}

function generateBusinessIntelligence(data: ProcessedData): string {
  const { summary, rows, headers } = data;
  let intelligence = '';

  // Identify key performance indicators
  const possibleKPIs = headers.filter(header => 
    header.toLowerCase().includes('sales') ||
    header.toLowerCase().includes('revenue') ||
    header.toLowerCase().includes('profit') ||
    header.toLowerCase().includes('cost') ||
    header.toLowerCase().includes('price') ||
    header.toLowerCase().includes('quantity') ||
    header.toLowerCase().includes('rating') ||
    header.toLowerCase().includes('score')
  );

  if (possibleKPIs.length > 0) {
    intelligence += 'Key Performance Indicators Identified:\n';
    possibleKPIs.forEach(kpi => {
      const stats = summary.columnStats[kpi];
      if (stats.mean && summary.numericalColumns.includes(kpi)) {
        intelligence += `• ${kpi}: Average ${stats.mean.toFixed(2)}\n`;
        if (stats.min !== undefined && stats.max !== undefined) {
          intelligence += `  - Performance Range: ${stats.min} to ${stats.max}\n`;
        }
      }
    });
  }

  // Business trends analysis
  const timeColumns = headers.filter(header => 
    header.toLowerCase().includes('date') ||
    header.toLowerCase().includes('time') ||
    header.toLowerCase().includes('year') ||
    header.toLowerCase().includes('month')
  );

  if (timeColumns.length > 0) {
    intelligence += '\nTime-Based Analysis:\n';
    intelligence += `• Time Dimension: ${timeColumns[0]} available for trend analysis\n`;
    intelligence += `• Data Span: ${rows.length} time points captured\n`;
    intelligence += `• Trend Analysis: Suitable for seasonal patterns and forecasting\n`;
  }

  // Market segments
  const segmentColumns = headers.filter(header => 
    header.toLowerCase().includes('category') ||
    header.toLowerCase().includes('type') ||
    header.toLowerCase().includes('segment') ||
    header.toLowerCase().includes('region') ||
    header.toLowerCase().includes('product') ||
    header.toLowerCase().includes('customer')
  );

  if (segmentColumns.length > 0) {
    intelligence += '\nMarket Segmentation Opportunities:\n';
    segmentColumns.forEach(segment => {
      const stats = summary.columnStats[segment];
      if (stats.uniqueValues) {
        intelligence += `• ${segment}: ${stats.uniqueValues} distinct segments identified\n`;
        if (stats.mostCommon && stats.mostCommon.length > 0) {
          intelligence += `  - Largest Segment: ${stats.mostCommon[0].value} (${stats.mostCommon[0].percentage.toFixed(1)}%)\n`;
        }
      }
    });
  }

  // Data completeness for business decisions
  intelligence += '\nData Readiness for Business Intelligence:\n';
  const completeColumns = Object.entries(summary.columnStats).filter(([_, stats]) => {
    return stats.totalCount === rows.length;
  }).length;
  
  const completenessRatio = completeColumns / headers.length;
  if (completenessRatio > 0.9) {
    intelligence += '• Data Quality: Excellent - Ready for advanced analytics and ML\n';
  } else if (completenessRatio > 0.7) {
    intelligence += '• Data Quality: Good - Suitable for most business analyses\n';
  } else {
    intelligence += '• Data Quality: Needs improvement - Consider data cleaning\n';
  }

  return intelligence;
}

function detectAnomalies(data: ProcessedData): string {
  const { summary, rows } = data;
  let anomalies = '';

  // Numerical outliers detection
  if (summary.numericalColumns.length > 0) {
    anomalies += 'Numerical Outlier Analysis:\n';
    
    summary.numericalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.mean && stats.stdDev && stats.min !== undefined && stats.max !== undefined) {
        const values = rows.map(row => Number(row[column])).filter(v => !isNaN(v));
        
        // Calculate potential outliers using IQR method
        values.sort((a, b) => a - b);
        const q1 = values[Math.floor(values.length * 0.25)];
        const q3 = values[Math.floor(values.length * 0.75)];
        const iqr = q3 - q1;
        const lowerBound = q1 - 1.5 * iqr;
        const upperBound = q3 + 1.5 * iqr;
        
        const outliers = values.filter(v => v < lowerBound || v > upperBound);
        const outlierPercentage = (outliers.length / values.length) * 100;
        
        anomalies += `• ${column}:\n`;
        if (outlierPercentage > 5) {
          anomalies += `  - Potential outliers detected: ${outliers.length} values (${outlierPercentage.toFixed(1)}%)\n`;
          anomalies += `  - Outlier range: Below ${lowerBound.toFixed(2)} or above ${upperBound.toFixed(2)}\n`;
        } else {
          anomalies += `  - Data appears clean with minimal outliers (${outlierPercentage.toFixed(1)}%)\n`;
        }
      }
    });
  }

  // Categorical anomalies
  if (summary.categoricalColumns.length > 0) {
    anomalies += '\nCategorical Data Anomalies:\n';
    
    summary.categoricalColumns.forEach(column => {
      const stats = summary.columnStats[column];
      if (stats.mostCommon && stats.uniqueValues && stats.totalCount) {
        const rareCategoriesCount = stats.mostCommon.filter(cat => cat.percentage < 1).length;
        
        anomalies += `• ${column}:\n`;
        if (rareCategoriesCount > 0) {
          anomalies += `  - Rare categories: ${rareCategoriesCount} categories with <1% frequency\n`;
          anomalies += `  - Consider grouping rare categories for analysis\n`;
        } else {
          anomalies += `  - No rare categories detected - good distribution\n`;
        }
      }
    });
  }

  return anomalies;
}

async function generateAIInsights(data: ProcessedData): Promise<string> {
  try {
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    
    if (!apiKey) {
      throw new Error('Missing API key for insights generation');
    }
    
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
    
    // Prepare data summary for AI analysis
    const dataSummary = {
      totalRows: data.summary.rowCount,
      totalColumns: data.summary.columnCount,
      numericalColumns: data.summary.numericalColumns,
      categoricalColumns: data.summary.categoricalColumns,
      columnStats: Object.fromEntries(
        Object.entries(data.summary.columnStats).map(([col, stats]: [string, any]) => [
          col,
          {
            type: data.summary.numericalColumns.includes(col) ? 'numerical' : 'categorical',
            ...(stats.mean !== undefined ? {
              min: stats.min,
              max: stats.max,
              mean: stats.mean,
              stdDev: stats.stdDev
            } : {
              uniqueValues: stats.uniqueValues,
              topValues: stats.mostCommon?.slice(0, 3)
            })
          }
        ])
      )
    };
    
    const prompt = `You are a world-class data analyst providing a report on the following dataset.

**Dataset Summary:**
\`\`\`json
${JSON.stringify(dataSummary, null, 2)}
\`\`\`

**Instructions:**
Generate a professional, insightful, and well-structured data analysis report in **Markdown format**.

The report should include the following sections:
- **\`## Executive Summary\`**: A high-level overview of the most critical findings and business implications.
- **\`## Key Findings & Patterns\`**: Detailed discoveries, trends, and significant data characteristics. Use bullet points.
- **\`## Business Intelligence Insights\`**: How the data relates to business performance, KPIs, and market behavior.
- **\`## Data Quality & Reliability Assessment\`**: An analysis of data completeness, potential issues, and its reliability for decision-making.
- **\`## Actionable Recommendations\`**: Specific, data-driven actions to take, areas for further investigation, and potential data collection improvements.

**Formatting Requirements:**
- Use Markdown for all formatting (e.g., \`##\` for H2, \`###\` for H3, \`**\` for bold, \`*\` for italics, \`*\` for list items, and \`\` for code snippets).
- Do NOT include a main title (\`# Report Title\`) in your response. The title is handled separately.
- Be concise yet comprehensive. Focus on insights that provide business value.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const insights = response.text();
    
    return insights;
    
  } catch (error) {
    console.error('Error generating AI insights:', error);
    return "### AI Insights Generation Failed\n\nWe were unable to generate AI-powered insights for your data at this time. This could be due to a network issue or a problem with the API key.\n\nPlease check your configuration and try again. The basic data summary is still available below.";
  }
}

function generateBasicReport(reportData: ReportData): string {
  const { processedData, timestamp } = reportData;
  const { summary, headers, rows } = processedData;
  
  return `
BASIC DATA INSIGHTS REPORT
Generated on: ${timestamp.toLocaleDateString()} at ${timestamp.toLocaleTimeString()}
================================================================================

DATASET OVERVIEW
================================================================================
• Total Rows: ${summary.rowCount.toLocaleString()}
• Total Columns: ${summary.columnCount.toLocaleString()}
• Numerical Columns: ${summary.numericalColumns.length}
• Categorical Columns: ${summary.categoricalColumns.length}

BASIC INSIGHTS
================================================================================
AI-powered insights could not be generated. Please check your API key and network connection.
This basic report contains a summary of the data structure. For full analysis, please resolve any connection issues and try again.

DATA QUALITY ASSESSMENT
================================================================================
${analyzeDataQuality(processedData)}

================================================================================
Report generated by DataAnalytics Platform (Basic Mode)
Dataset contains ${rows.length.toLocaleString()} rows across ${headers.length} columns
================================================================================
`;
}

function generateFallbackInsights(data: ProcessedData): string {
  const { summary } = data;
  let insights = '';
  
  insights += 'BASIC DATA ANALYSIS:\n\n';
  
  insights += '• Dataset Characteristics:\n';
  insights += `  - Size: ${summary.rowCount.toLocaleString()} records across ${summary.columnCount} columns\n`;
  insights += `  - Data Mix: ${summary.numericalColumns.length} numerical, ${summary.categoricalColumns.length} categorical columns\n\n`;
  
  if (summary.numericalColumns.length > 0) {
    insights += '• Numerical Data Insights:\n';
    summary.numericalColumns.forEach(col => {
      const stats = summary.columnStats[col] as any;
      if (stats.mean !== undefined) {
        insights += `  - ${col}: Average ${stats.mean.toFixed(2)}, Range ${stats.min} to ${stats.max}\n`;
      }
    });
    insights += '\n';
  }
  
  if (summary.categoricalColumns.length > 0) {
    insights += '• Categorical Data Insights:\n';
    summary.categoricalColumns.forEach(col => {
      const stats = summary.columnStats[col] as any;
      if (stats.uniqueValues) {
        insights += `  - ${col}: ${stats.uniqueValues} unique categories\n`;
      }
    });
  }
  
  return insights;
} 