import { ProcessedData } from '../store/dataStore';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { saveAs } from 'file-saver';
import { marked } from 'marked';
import { llmMonitor } from './llmMonitor';

export interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  generatePrompt: (data: ProcessedData) => string;
  formatOutput: (aiResponse: string, data: ProcessedData) => string;
}

export const reportTemplates: ReportTemplate[] = [
  {
    id: 'data-analysis',
    name: 'Data Analysis Report',
    description: 'Comprehensive data insights and visualizations',
    icon: 'BarChart2',
    generatePrompt: (data: ProcessedData) => `
You are a senior data analyst creating a comprehensive data analysis report. Analyze the following dataset:

**Dataset Overview:**
- Rows: ${data.summary.rowCount.toLocaleString()}
- Columns: ${data.summary.columnCount}
- Numerical columns: ${data.summary.numericalColumns.join(', ') || 'None'}
- Categorical columns: ${data.summary.categoricalColumns.join(', ') || 'None'}

**Column Statistics:**
${JSON.stringify(data.summary.columnStats, null, 2)}

Create a professional data analysis report in Markdown format with these sections:

## Executive Summary
- Key findings and insights
- Data quality assessment
- Business implications

## Detailed Analysis
- Statistical insights for numerical data
- Distribution patterns for categorical data
- Correlations and relationships
- Trends and patterns

## Data Quality Assessment
- Completeness analysis
- Outliers and anomalies
- Data reliability score

## Recommendations
- Data-driven insights
- Areas for further investigation
- Data collection improvements

Focus on actionable insights that can drive business decisions.
    `,
    formatOutput: (aiResponse: string, data: ProcessedData) => {
      return `# Data Analysis Report
Generated on: ${new Date().toLocaleDateString()}

${aiResponse}

---
*Report generated by DataAnalytics AI Platform*
*Dataset: ${data.summary.rowCount.toLocaleString()} rows × ${data.summary.columnCount} columns*`;
    }
  },
  {
    id: 'statistical-summary',
    name: 'Statistical Summary',
    description: 'Statistical analysis and data distribution',
    icon: 'TrendingUp',
    generatePrompt: (data: ProcessedData) => `
You are a statistician creating a detailed statistical summary report. Analyze this dataset:

**Dataset Statistics:**
- Sample size: ${data.summary.rowCount.toLocaleString()} observations
- Variables: ${data.summary.columnCount} total
- Numerical variables: ${data.summary.numericalColumns.length}
- Categorical variables: ${data.summary.categoricalColumns.length}

**Detailed Statistics:**
${JSON.stringify(data.summary.columnStats, null, 2)}

Create a comprehensive statistical report in Markdown format with:

## Descriptive Statistics Summary
- Central tendency measures
- Variability measures
- Distribution characteristics

## Numerical Variables Analysis
- Mean, median, mode analysis
- Standard deviation and variance
- Range and percentiles
- Skewness and kurtosis insights

## Categorical Variables Analysis
- Frequency distributions
- Mode analysis
- Diversity indices
- Category concentration

## Statistical Significance
- Sample size adequacy
- Confidence intervals (where applicable)
- Statistical power assessment

## Distribution Patterns
- Normal distribution tests
- Outlier detection
- Data transformation recommendations

Focus on statistical rigor and mathematical accuracy.
    `,
    formatOutput: (aiResponse: string, data: ProcessedData) => {
      return `# Statistical Summary Report
Analysis Date: ${new Date().toLocaleDateString()}

${aiResponse}

## Technical Details
- Analysis Method: Descriptive Statistics
- Sample Size: ${data.summary.rowCount.toLocaleString()}
- Confidence Level: 95%
- Statistical Software: DataAnalytics Platform

---
*Statistical analysis performed using advanced AI algorithms*`;
    }
  },
  {
    id: 'data-quality',
    name: 'Data Quality Report',
    description: 'Data completeness and quality metrics',
    icon: 'FileText',
    generatePrompt: (data: ProcessedData) => `
You are a data quality specialist creating a comprehensive data quality assessment. Evaluate this dataset:

**Dataset Profile:**
- Total records: ${data.summary.rowCount.toLocaleString()}
- Total fields: ${data.summary.columnCount}
- Data types: ${data.summary.numericalColumns.length} numerical, ${data.summary.categoricalColumns.length} categorical

**Field Analysis:**
${JSON.stringify(data.summary.columnStats, null, 2)}

Create a thorough data quality report in Markdown format covering:

## Data Quality Executive Summary
- Overall quality score
- Critical issues identified
- Readiness for analysis

## Completeness Assessment
- Missing value analysis
- Data availability by field
- Completeness scoring

## Accuracy & Consistency
- Data type validation
- Range validation for numerical fields
- Format consistency for categorical fields

## Data Integrity
- Duplicate detection
- Referential integrity
- Constraint violations

## Outlier & Anomaly Detection
- Statistical outliers
- Business rule violations
- Unusual patterns

## Data Quality Recommendations
- Immediate fixes required
- Data cleansing strategies
- Prevention measures

## Quality Metrics Dashboard
- Overall quality score
- Field-level quality scores
- Trend analysis

Provide specific, actionable recommendations for data quality improvement.
    `,
    formatOutput: (aiResponse: string, data: ProcessedData) => {
      return `# Data Quality Assessment Report
Assessment Date: ${new Date().toLocaleDateString()}

${aiResponse}

## Quality Metrics Summary
- **Dataset Size**: ${data.summary.rowCount.toLocaleString()} records
- **Field Count**: ${data.summary.columnCount} fields
- **Data Types**: ${data.summary.numericalColumns.length} numerical, ${data.summary.categoricalColumns.length} categorical
- **Assessment Method**: Automated AI-powered analysis

---
*Quality assessment powered by DataAnalytics AI Platform*`;
    }
  },
  {
    id: 'performance-metrics',
    name: 'Performance Metrics',
    description: 'Key performance indicators and trends',
    icon: 'Activity',
    generatePrompt: (data: ProcessedData) => `
You are a business performance analyst creating a KPI and performance metrics report. Analyze this dataset for business performance insights:

**Business Data Overview:**
- Records: ${data.summary.rowCount.toLocaleString()}
- Metrics: ${data.summary.columnCount}
- Numerical KPIs: ${data.summary.numericalColumns.join(', ') || 'None'}
- Categorical Dimensions: ${data.summary.categoricalColumns.join(', ') || 'None'}

**Performance Data:**
${JSON.stringify(data.summary.columnStats, null, 2)}

Create a business performance report in Markdown format with:

## Performance Dashboard Summary
- Key performance indicators
- Performance trends
- Critical metrics status

## KPI Analysis
- Primary KPIs identification
- Performance benchmarking
- Target vs actual analysis

## Trend Analysis
- Performance over time (if temporal data exists)
- Growth patterns
- Seasonal variations

## Performance Segmentation
- Performance by category/segment
- Top and bottom performers
- Performance distribution

## Business Insights
- Performance drivers
- Risk indicators
- Opportunity areas

## Performance Recommendations
- Performance improvement strategies
- Metric optimization
- Action items

## Performance Scorecard
- Overall performance rating
- Individual metric scores
- Performance summary

Focus on business value and actionable performance insights.
    `,
    formatOutput: (aiResponse: string, data: ProcessedData) => {
      return `# Performance Metrics Report
Report Period: ${new Date().toLocaleDateString()}

${aiResponse}

## Performance Summary
- **Data Points Analyzed**: ${data.summary.rowCount.toLocaleString()}
- **Performance Metrics**: ${data.summary.columnCount}
- **Analysis Type**: Comprehensive Performance Assessment
- **Report Generated**: ${new Date().toLocaleString()}

---
*Performance analysis powered by DataAnalytics Business Intelligence*`;
    }
  }
];

export async function generateReport(
  templateId: string, 
  data: ProcessedData, 
  format: 'pdf' | 'html' | 'txt' = 'html'
): Promise<{ success: boolean; fileName?: string; error?: string }> {
  const callId = llmMonitor.startCall('report');
  
  try {
    const template = reportTemplates.find(t => t.id === templateId);
    if (!template) {
      throw new Error(`Report template ${templateId} not found`);
    }

    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('Missing API key for report generation');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    // Generate the AI response
    const prompt = template.generatePrompt(data);
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const aiResponse = response.text();

    // Format the output
    const formattedContent = template.formatOutput(aiResponse, data);

    // Generate file based on format
    const timestamp = new Date().toISOString().split('T')[0];
    let fileName: string;
    let blob: Blob;

    switch (format) {
      case 'html':
        const htmlContent = await convertToHTML(formattedContent, template.name);
        fileName = `${template.id}-report-${timestamp}.html`;
        blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
        break;
      
      case 'txt':
        fileName = `${template.id}-report-${timestamp}.txt`;
        blob = new Blob([formattedContent], { type: 'text/plain;charset=utf-8' });
        break;
      
      case 'pdf':
        // For PDF, we'll create an HTML version and let the user print to PDF
        const pdfHtmlContent = await convertToHTML(formattedContent, template.name, true);
        fileName = `${template.id}-report-${timestamp}.html`;
        blob = new Blob([pdfHtmlContent], { type: 'text/html;charset=utf-8' });
        break;
      
      default:
        throw new Error(`Unsupported format: ${format}`);
    }

    saveAs(blob, fileName);
    llmMonitor.completeCall(callId);
    return { success: true, fileName };

  } catch (error) {
    console.error('Error generating report:', error);
    llmMonitor.failCall(callId, error instanceof Error ? error.message : 'Unknown error occurred');
    return { 
      success: false, 
      error: error instanceof Error ? error.message : 'Unknown error occurred' 
    };
  }
}

async function convertToHTML(markdownContent: string, reportTitle: string, isPrintFriendly: boolean = false): Promise<string> {
  const htmlBody = marked.parse(markdownContent);
  
  const printStyles = isPrintFriendly ? `
    @media print {
      body { -webkit-print-color-adjust: exact; }
      .no-print { display: none; }
    }
    .print-button {
      position: fixed;
      top: 20px;
      right: 20px;
      background: #0052A5;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      font-weight: bold;
    }
    .print-button:hover {
      background: #003d7a;
    }
  ` : '';

  const printButton = isPrintFriendly ? `
    <button class="print-button no-print" onclick="window.print()">
      🖨️ Print to PDF
    </button>
  ` : '';

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${reportTitle}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            background-color: #ffffff;
            color: #333333;
            max-width: 800px;
            margin: 0 auto;
        }
        .container {
            background: #ffffff;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1, h2, h3, h4 {
            color: #0052A5;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 8px;
            margin-top: 32px;
        }
        h1 { 
            font-size: 2.5em; 
            text-align: center; 
            border-bottom: 3px solid #0052A5;
            margin-bottom: 30px;
        }
        h2 { font-size: 1.8em; }
        h3 { font-size: 1.4em; }
        h4 { font-size: 1.2em; color: #666; }
        
        p { margin-bottom: 16px; }
        ul, ol { padding-left: 24px; }
        li { margin-bottom: 8px; }
        
        strong { color: #0052A5; font-weight: 600; }
        em { color: #666; }
        
        pre {
            background: #f8f9fa;
            padding: 16px;
            border-radius: 6px;
            border-left: 4px solid #0052A5;
            overflow-x: auto;
            font-family: 'Courier New', Courier, monospace;
        }
        
        code {
            background-color: #f1f3f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', Courier, monospace;
            font-size: 0.9em;
        }
        
        blockquote {
            border-left: 4px solid #0052A5;
            margin: 16px 0;
            padding: 16px 20px;
            background: #f8f9fa;
            border-radius: 0 6px 6px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        th, td {
            border: 1px solid #e5e7eb;
            padding: 12px;
            text-align: left;
        }
        
        th {
            background: #0052A5;
            color: white;
            font-weight: 600;
        }
        
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        
        .timestamp {
            text-align: center;
            color: #666;
            font-style: italic;
            margin-bottom: 30px;
            padding: 10px;
            background: #f8f9fa;
            border-radius: 6px;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }
        
        ${printStyles}
    </style>
</head>
<body>
    ${printButton}
    <div class="container">
        <div class="timestamp">
            Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
        </div>
        
        ${htmlBody}
        
        <div class="footer">
            <p><strong>Report generated by DataAnalytics AI Platform</strong></p>
            <p>© ${new Date().getFullYear()} DataAnalytics. All rights reserved.</p>
        </div>
    </div>
</body>
</html>`;
}

export function getReportTemplate(templateId: string): ReportTemplate | undefined {
  return reportTemplates.find(t => t.id === templateId);
}

export function getAllReportTemplates(): ReportTemplate[] {
  return reportTemplates;
}
